[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
via_ir = true
verbosity = 2
ffi = true

remappings = [
  "@openzeppelin-contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.5.0",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.5.0",
  "forge-std/=dependencies/forge-std-1.11.0/src",
]

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.5.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"

[fmt]
line_length = 160
number_underscore = "thousands"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon_pos = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_pos = { key = "${POLYGONSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
